package com.loyaltyglobal.util

import com.loyaltyglobal.data.model.CountryCodeData

/**
 * Created by Abhin.
 */

object Constants {
    const val UNAUTHORISED = 401

    const val REGEX_EMAIL = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$"
    const val PASSWORD_PATTERN = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{6,}"
    const val PASSWORD_PATTERN_WITH_ONE_SPECIAL_CHARS = "^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[@\$!%*#?&])[A-Za-z\\d@\$!%*#?&]{8,}\$"

    fun setCountryList(): ArrayList<CountryCodeData> {
        val mCountryList = ArrayList<CountryCodeData>()
        mCountryList.add(CountryCodeData(key = "AF", countryName = "Afghanistan", countryCode = "+93"))
        mCountryList.add(
            CountryCodeData(
                key = "AX",
                countryName = "Åland Islands",
                countryCode = "+358"
            )
        )
        mCountryList.add(CountryCodeData(key = "AL", countryName = "Albania", countryCode = "+355"))
        mCountryList.add(CountryCodeData(key = "DZ", countryName = "Algeria", countryCode = "+213"))
        mCountryList.add(
            CountryCodeData(
                key = "AS",
                countryName = "American Samoa",
                countryCode = "+1684"
            )
        )
        mCountryList.add(CountryCodeData(key = "AD", countryName = "Andorra", countryCode = "+376"))
        mCountryList.add(CountryCodeData(key = "AO", countryName = "Angola", countryCode = "+244"))
        mCountryList.add(CountryCodeData(key = "AI", countryName = "Anguilla", countryCode = "+1264"))
        mCountryList.add(CountryCodeData(key = "AQ", countryName = "Antarctica", countryCode = "+672"))
        mCountryList.add(
            CountryCodeData(
                key = "AG",
                countryName = "Antigua and Barbuda",
                countryCode = "+1268"
            )
        )
        mCountryList.add(CountryCodeData(key = "AR", countryName = "Argentina", countryCode = "+54"))
        mCountryList.add(CountryCodeData(key = "AM", countryName = "Armenia", countryCode = "+374"))
        mCountryList.add(CountryCodeData(key = "AW", countryName = "Aruba", countryCode = "+297"))
        mCountryList.add(CountryCodeData(key = "AU", countryName = "Australia", countryCode = "+61"))
        mCountryList.add(CountryCodeData(key = "AT", countryName = "Austria", countryCode = "+43"))
        mCountryList.add(CountryCodeData(key = "AZ", countryName = "Azerbaijan", countryCode = "+994"))
        mCountryList.add(CountryCodeData(key = "BS", countryName = "Bahamas", countryCode = "+1242"))
        mCountryList.add(CountryCodeData(key = "BH", countryName = "Bahrain", countryCode = "+973"))
        mCountryList.add(CountryCodeData(key = "BD", countryName = "Bangladesh", countryCode = "+880"))
        mCountryList.add(CountryCodeData(key = "BB", countryName = "Barbados", countryCode = "+1246"))
        mCountryList.add(CountryCodeData(key = "BY", countryName = "Belarus", countryCode = "+375"))
        mCountryList.add(CountryCodeData(key = "BE", countryName = "Belgium", countryCode = "+32"))
        mCountryList.add(CountryCodeData(key = "BZ", countryName = "Belize", countryCode = "+501"))
        mCountryList.add(CountryCodeData(key = "BJ", countryName = "Benin", countryCode = "+229"))
        mCountryList.add(CountryCodeData(key = "BM", countryName = "Bermuda", countryCode = "+1441"))
        mCountryList.add(CountryCodeData(key = "BT", countryName = "Bhutan", countryCode = "+975"))
        mCountryList.add(
            CountryCodeData(
                key = "BO",
                countryName = "Bolivia, Plurinational State of bolivia",
                countryCode = "+591"
            )
        )
        mCountryList.add(CountryCodeData("BA", "Bosnia and Herzegovina", countryCode = "+387"))
        mCountryList.add(CountryCodeData("BW", "Botswana", countryCode = "+267"))
        mCountryList.add(CountryCodeData("BV", "Bouvet Island", countryCode = "+47"))
        mCountryList.add(CountryCodeData("BR", "Brazil", countryCode = "+55"))
        mCountryList.add(CountryCodeData("IO", "British Indian Ocean Territory", countryCode = "+246"))
        mCountryList.add(CountryCodeData("BN", "Brunei Darussalam", countryCode = "+673"))
        mCountryList.add(CountryCodeData("BG", "Bulgaria", countryCode = "+359"))
        mCountryList.add(CountryCodeData("BF", "Burkina Faso", countryCode = "+226"))
        mCountryList.add(CountryCodeData("BI", "Burundi", countryCode = "+257"))
        mCountryList.add(CountryCodeData("KH", "Cambodia", countryCode = "+855"))
        mCountryList.add(CountryCodeData("CM", "Cameroon", countryCode = "+237"))
        mCountryList.add(CountryCodeData("CA", "Canada", countryCode = "+1"))
        mCountryList.add(CountryCodeData("CV", "Cape Verde", countryCode = "+238"))
        mCountryList.add(CountryCodeData("KY", "Cayman Islands", countryCode = "+345"))
        mCountryList.add(CountryCodeData("CF", "Central African Republic", countryCode = "+236"))
        mCountryList.add(CountryCodeData("TD", "Chad ", countryCode = "+235"))
        mCountryList.add(CountryCodeData("CL", "Chile", countryCode = "+56"))
        mCountryList.add(CountryCodeData("CN", "China", countryCode = "+86"))
        mCountryList.add(CountryCodeData("CX", "Christmas Island", countryCode = "+61"))
        mCountryList.add(CountryCodeData("CC", "Cocos (Keeling) Islands", countryCode = "+61"))
        mCountryList.add(CountryCodeData("CO", "Colombia", "+57"))
        mCountryList.add(CountryCodeData("KM", "Comoros", countryCode = "+269"))
        mCountryList.add(CountryCodeData("CG", "Congo", countryCode = "+242"))
        mCountryList.add(
            CountryCodeData(
                "CD",
                "Congo, The Democratic Republic of the Congo",
                countryCode = "+243"
            )
        )
        mCountryList.add(CountryCodeData("CK", "Cook Islands", countryCode = "+682"))
        mCountryList.add(CountryCodeData("CR", "Costa Rica", countryCode = "+506"))
        mCountryList.add(CountryCodeData("CI", "Cote d'Ivoire", "+225"))
        mCountryList.add(CountryCodeData("HR", "Croatia", countryCode = "+385"))
        mCountryList.add(CountryCodeData("CU", "Cuba", countryCode = "+53"))
        mCountryList.add(CountryCodeData("CY", "Cyprus", countryCode = "+357"))
        mCountryList.add(CountryCodeData("CZ", "Czech Republic", countryCode = "+420"))
        mCountryList.add(CountryCodeData("DK", "Denmark", countryCode = "+45"))
        mCountryList.add(CountryCodeData("DJ", "Djibouti", countryCode = "+253"))
        mCountryList.add(CountryCodeData("DM", "Dominica", countryCode = "+1767"))
        mCountryList.add(CountryCodeData("DO", "Dominican Republic", countryCode = "+1849"))
        mCountryList.add(CountryCodeData("EC", "Ecuador ", countryCode = "+593"))
        mCountryList.add(CountryCodeData("EG", "Egypt", countryCode = "+20"))
        mCountryList.add(CountryCodeData("SV", "El Salvador", countryCode = "+503"))
        mCountryList.add(CountryCodeData("GQ", "Equatorial Guinea", countryCode = "+240"))
        mCountryList.add(CountryCodeData("ER", "Eritrea", countryCode = "+291"))
        mCountryList.add(CountryCodeData("EE", "Estonia", countryCode = "+372"))
        mCountryList.add(CountryCodeData("ET", "Ethiopia", countryCode = "+251"))
        mCountryList.add(CountryCodeData("FK", "Falkland Islands (Malvinas", countryCode = "+500"))
        mCountryList.add(CountryCodeData("FO", "Faroe Islands", countryCode = "+298"))
        mCountryList.add(CountryCodeData("FJ", "Fiji", countryCode = "+679"))
        mCountryList.add(CountryCodeData("FI", "Finland", countryCode = "+358"))
        mCountryList.add(CountryCodeData("FR", "France", countryCode = "+33"))
        mCountryList.add(CountryCodeData("GF", "French Guiana", countryCode = "+594"))
        mCountryList.add(CountryCodeData("PF", "French Polynesia", countryCode = "+689"))
        mCountryList.add(CountryCodeData("TF", "French Southern Territories", countryCode = "+262"))
        mCountryList.add(CountryCodeData("GA", "Gabon", countryCode = "+241"))
        mCountryList.add(CountryCodeData("GM", "Gambia", countryCode = "+220"))
        mCountryList.add(CountryCodeData("GE", "Georgia", countryCode = "+995"))
        mCountryList.add(CountryCodeData("DE", "Germany", countryCode = "+49"))
        mCountryList.add(CountryCodeData("GH", "Ghana", "+233"))
        mCountryList.add(CountryCodeData("GI", "Gibraltar", "+350"))
        mCountryList.add(CountryCodeData("GR", "Greece", "+30"))
        mCountryList.add(CountryCodeData("GL", "Greenland", "+299"))
        mCountryList.add(CountryCodeData("GD", "Grenada", "+1473"))
        mCountryList.add(CountryCodeData("GP", "Guadeloupe", "+590"))
        mCountryList.add(CountryCodeData("GU", "Guam", "+1671"))
        mCountryList.add(CountryCodeData("GT", "Guatemala", "+502"))
        mCountryList.add(CountryCodeData("GG", "Guernsey", "+44"))
        mCountryList.add(CountryCodeData("GN", "Guinea ", "+224"))
        mCountryList.add(CountryCodeData("GW", "Guinea-Bissau ", "+245"))
        mCountryList.add(CountryCodeData("GY", "Guyana ", "+592"))
        mCountryList.add(CountryCodeData("HT", "Haiti ", "+509"))
        mCountryList.add(CountryCodeData("HM", "Heard Island and Mcdonald Islands ", "+672"))
        mCountryList.add(CountryCodeData("VA", "Holy See (Vatican City State) ", "+379"))
        mCountryList.add(CountryCodeData("HN", "Honduras ", "+504"))
        mCountryList.add(CountryCodeData("HK", "Hong Kong ", "+852"))
        mCountryList.add(CountryCodeData("HU", "Hungary ", "+36"))
        mCountryList.add(CountryCodeData("IS", "Iceland ", "+354"))
        mCountryList.add(CountryCodeData("IN", "India ", "+91"))
        mCountryList.add(CountryCodeData("ID", "Indonesia ", "+62"))
        mCountryList.add(CountryCodeData("IR", "Iran, Islamic Republic of Persian Gulf ", "+98"))
        mCountryList.add(CountryCodeData("IQ", "Iraq ", "+964"))
        mCountryList.add(CountryCodeData("IE", "Ireland ", "+353"))
        mCountryList.add(CountryCodeData("IM", "Isle of Man ", "+44"))
        mCountryList.add(CountryCodeData("IL", "Israel ", "+972"))
        mCountryList.add(CountryCodeData("IT", "Italia ", "+39"))
        mCountryList.add(CountryCodeData("JM", "Jamaica ", "+1876"))
        mCountryList.add(CountryCodeData("JP", "Japan ", "+81"))
        mCountryList.add(CountryCodeData("JE", "Jersey ", "+44"))
        mCountryList.add(CountryCodeData("JO", "Jordan ", "+962"))
        mCountryList.add(CountryCodeData("KZ", "Kazakhstan ", "+7"))
        mCountryList.add(CountryCodeData("KE", "Kenya ", "+254"))
        mCountryList.add(CountryCodeData("KI", "Kiribati ", "+686"))
        mCountryList.add(CountryCodeData("KP", "Korea, Democratic People's Republic of Korea ", "+850"))
        mCountryList.add(CountryCodeData("KR", "Korea, Republic of South Korea ", "+82"))
        mCountryList.add(CountryCodeData("XK", "Kosovo ", "+383"))
        mCountryList.add(CountryCodeData("KW", "Kuwait ", "+965"))
        mCountryList.add(CountryCodeData("KG", "Kyrgyzstan ", "+996"))
        mCountryList.add(CountryCodeData("LA", "Laos ", "+856"))
        mCountryList.add(CountryCodeData("LV", "Latvia ", "+371"))
        mCountryList.add(CountryCodeData("LB", "Lebanon ", "+961"))
        mCountryList.add(CountryCodeData("LS", "Lesotho ", "+266"))
        mCountryList.add(CountryCodeData("LR", "Liberia ", "+231"))
        mCountryList.add(CountryCodeData("LY", "Libyan Arab Jamahiriya ", "+218"))
        mCountryList.add(CountryCodeData("LI", "Liechtenstein ", "+423"))
        mCountryList.add(CountryCodeData("LT", "Lithuania ", "+370"))
        mCountryList.add(CountryCodeData("LU", "Luxembourg ", "+352"))
        mCountryList.add(CountryCodeData("MO", "Macao ", "+853"))
        mCountryList.add(CountryCodeData("MK", "Macedonia ", "+389"))
        mCountryList.add(CountryCodeData("MG", "Madagascar ", "+261"))
        mCountryList.add(CountryCodeData("MW", "Malawi ", "+265"))
        mCountryList.add(CountryCodeData("MY", "Malaysia ", "+60"))
        mCountryList.add(CountryCodeData("MV", "Maldives ", "+960"))
        mCountryList.add(CountryCodeData("ML", "Mali ", "+223"))
        mCountryList.add(CountryCodeData("MT", "Malta ", "+356"))
        mCountryList.add(CountryCodeData("MH", "Marshall Islands ", "+692"))
        mCountryList.add(CountryCodeData("MQ", "Martinique ", "+596"))
        mCountryList.add(CountryCodeData("MR", "Mauritania ", "+222"))
        mCountryList.add(CountryCodeData("MU", "Mauritius ", "+230"))
        mCountryList.add(CountryCodeData("YT", "Mayotte ", "+262"))
        mCountryList.add(CountryCodeData("MX", "Mexico ", "+52"))
        mCountryList.add(CountryCodeData("FM", "Micronesia, Federated States of Micronesia ", "+691"))
        mCountryList.add(CountryCodeData("MD", "Moldova ", "+373"))
        mCountryList.add(CountryCodeData("MC", "Monaco ", "+377"))
        mCountryList.add(CountryCodeData("MN", "Mongolia ", "+976"))
        mCountryList.add(CountryCodeData("ME", "Montenegro ", "+382"))
        mCountryList.add(CountryCodeData("MS", "Montserrat ", "+1664"))
        mCountryList.add(CountryCodeData("MA", "Morocco ", "+212"))
        mCountryList.add(CountryCodeData("MZ", "Mozambique ", "+258"))
        mCountryList.add(CountryCodeData("MM", "Myanmar ", "+95"))
        mCountryList.add(CountryCodeData("NA", "Namibia ", "+264"))
        mCountryList.add(CountryCodeData("NR", "Nauru ", "+674"))
        mCountryList.add(CountryCodeData("NP", "Nepal ", "+977"))
        mCountryList.add(CountryCodeData("NL", "Netherlands ", "+31"))
        mCountryList.add(CountryCodeData("AN", "Netherlands Antilles ", "+599"))
        mCountryList.add(CountryCodeData("NC", "New Caledonia ", "+687"))
        mCountryList.add(CountryCodeData("NZ", "New Zealand ", "+64"))
        mCountryList.add(CountryCodeData("NI", "Nicaragua ", "+505"))
        mCountryList.add(CountryCodeData("NE", "Niger ", "+227"))
        mCountryList.add(CountryCodeData("NG", "Nigeria ", "+234"))
        mCountryList.add(CountryCodeData("NU", "Niue ", "+683"))
        mCountryList.add(CountryCodeData("NF", "Norfolk Island ", "+672"))
        mCountryList.add(CountryCodeData("MP", "Northern Mariana Islands ", "+1670"))
        mCountryList.add(CountryCodeData("NO", "Norway ", "+47"))
        mCountryList.add(CountryCodeData("OM", "Oman ", "+968"))
        mCountryList.add(CountryCodeData("PK", "Pakistan ", "+92"))
        mCountryList.add(CountryCodeData("PW", "Palau ", "+680"))
        mCountryList.add(CountryCodeData("PS", "Palestinian Territory, Occupied ", "+970"))
        mCountryList.add(CountryCodeData("PA", "Panama ", "+507"))
        mCountryList.add(CountryCodeData("PG", "Papua New Guinea ", "+675"))
        mCountryList.add(CountryCodeData("PY", "Paraguay ", "+595"))
        mCountryList.add(CountryCodeData("PE", "Peru ", "+51"))
        mCountryList.add(CountryCodeData("PH", "Philippines ", "+63"))
        mCountryList.add(CountryCodeData("PN", "Pitcairn ", "+64"))
        mCountryList.add(CountryCodeData("PL", "Poland ", "+48"))
        mCountryList.add(CountryCodeData("PT", "Portugal ", "+351"))
        mCountryList.add(CountryCodeData("PR", "Puerto Rico ", "+1939"))
        mCountryList.add(CountryCodeData("QA", "Qatar ", "+974"))
        mCountryList.add(CountryCodeData("RO", "Romania ", "+40"))
        mCountryList.add(CountryCodeData("RU", "Russia ", "+7"))
        mCountryList.add(CountryCodeData("RW", "Rwanda ", "+250"))
        mCountryList.add(CountryCodeData("RE", "Reunion ", "+262"))
        mCountryList.add(CountryCodeData("BL", "Saint Barthelemy ", "+590"))
        mCountryList.add(CountryCodeData("SH", "Saint Helena, Ascension and Tristan Da Cunha ", "+290"))
        mCountryList.add(CountryCodeData("KN", "Saint Kitts and Nevis ", "+1869"))
        mCountryList.add(CountryCodeData("LC", "Saint Lucia ", "+1758"))
        mCountryList.add(CountryCodeData("MF", "Saint Martin ", "+590"))
        mCountryList.add(CountryCodeData("PM", "Saint Pierre and Miquelon ", "+508"))
        mCountryList.add(CountryCodeData("VC", "Saint Vincent and the Grenadines ", "+1784"))
        mCountryList.add(CountryCodeData("WS", "Samoa ", "+685"))
        mCountryList.add(CountryCodeData("SM", "San Marino ", "+378"))
        mCountryList.add(CountryCodeData("ST", "Sao Tome and Principe ", "+239"))
        mCountryList.add(CountryCodeData("SA", "Saudi Arabia ", "+966"))
        mCountryList.add(CountryCodeData("SN", "Senegal ", "+221"))
        mCountryList.add(CountryCodeData("RS", "Serbia ", "+381"))
        mCountryList.add(CountryCodeData("SC", "Seychelles ", "+248"))
        mCountryList.add(CountryCodeData("SL", "Sierra Leone ", "+232"))
        mCountryList.add(CountryCodeData("SG", "Singapore ", "+65"))
        mCountryList.add(CountryCodeData("SK", "Slovakia ", "+421"))
        mCountryList.add(CountryCodeData("SI", "Slovenia ", "+386"))
        mCountryList.add(CountryCodeData("SB", "Solomon Islands ", "+677"))
        mCountryList.add(CountryCodeData("SO", "Somalia ", "+252"))
        mCountryList.add(CountryCodeData("ZA", "South Africa ", "+27"))
        mCountryList.add(CountryCodeData("SS", "South Sudan ", "+211"))
        mCountryList.add(CountryCodeData("GS", "South Georgia and the South Sandwich Islands ", "+500"))
        mCountryList.add(CountryCodeData("ES", "Spain ", "+34"))
        mCountryList.add(CountryCodeData("LK", "Sri Lanka ", "+94"))
        mCountryList.add(CountryCodeData("SD", "Sudan ", "+249"))
        mCountryList.add(CountryCodeData("SR", "Suriname ", "+597"))
        mCountryList.add(CountryCodeData("SJ", "Svalbard and Jan Mayen ", "+47"))
        mCountryList.add(CountryCodeData("SZ", "Swaziland ", "+268"))
        mCountryList.add(CountryCodeData("SE", "Sweden ", "+46"))
        mCountryList.add(CountryCodeData("CH", "Switzerland ", "+41"))
        mCountryList.add(CountryCodeData("SY", "Syrian Arab Republic ", "+963"))
        mCountryList.add(CountryCodeData("TW", "Taiwan ", "+886"))
        mCountryList.add(CountryCodeData("TJ", "Tajikistan ", "+992"))
        mCountryList.add(CountryCodeData("TZ", "Tanzania, United Republic of Tanzania ", "+255"))
        mCountryList.add(CountryCodeData("TH", "Thailand ", "+66"))
        mCountryList.add(CountryCodeData("TL", "Timor-Leste ", "+670"))
        mCountryList.add(CountryCodeData("TG", "Togo ", "+228"))
        mCountryList.add(CountryCodeData("TK", "Tokelau ", "+690"))
        mCountryList.add(CountryCodeData("TO", "Tonga ", "+676"))
        mCountryList.add(CountryCodeData("TT", "Trinidad and Tobago ", "+1868"))
        mCountryList.add(CountryCodeData("TN", "Tunisia ", "+216"))
        mCountryList.add(CountryCodeData("TR", "Turkey ", "+90"))
        mCountryList.add(CountryCodeData("TM", "Turkmenistan ", "+993"))
        mCountryList.add(CountryCodeData("TC", "Turks and Caicos Islands ", "+1649"))
        mCountryList.add(CountryCodeData("TV", "Tuvalu ", "+688"))
        mCountryList.add(CountryCodeData("UG", "Uganda ", "+256"))
        mCountryList.add(CountryCodeData("UA", "Ukraine ", "+380"))
        mCountryList.add(CountryCodeData("AE", "United Arab Emirates ", "+971"))
        mCountryList.add(CountryCodeData("GB", "United Kingdom ", "+44"))
        mCountryList.add(CountryCodeData("US", "United States ", "+1"))
        mCountryList.add(CountryCodeData("UY", "Uruguay ", "+598"))
        mCountryList.add(CountryCodeData("UZ", "Uzbekistan ", "+998"))
        mCountryList.add(CountryCodeData("VU", "Vanuatu ", "+678"))
        mCountryList.add(CountryCodeData("VE", "Venezuela, Bolivarian Republic of Venezuela ", "+58"))
        mCountryList.add(CountryCodeData("VN", "Vietnam ", "+84"))
        mCountryList.add(CountryCodeData("VG", "Virgin Islands, British ", "+1284"))
        mCountryList.add(CountryCodeData("VI", "Virgin Islands, U.S. ", "+1340"))
        mCountryList.add(CountryCodeData("WF", "Wallis and Futuna ", "+681"))
        mCountryList.add(CountryCodeData("YE", "Yemen ", "+967"))
        mCountryList.add(CountryCodeData("ZM", "Zambia ", "+260"))
        mCountryList.add(CountryCodeData("ZW", "Zimbabwe ", "+263"))
        return mCountryList
    }
}

